Avoid parsing error when the type is reference type (#1604)
If defineProps is set as follows, the parser will error.
ref: #1579 

```ts
type Foo = {
  name: string
}

type Bar = Foo

// NG
defineProps<Bar>()

// OK
// defineProps<Foo>()
```

```
TypeError: Cannot read properties of undefined (reading 'length')
 ❯ NodePath.each ../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/path.ts:107:26
 ❯ getPropsFromLiteralType src/script-setup-handlers/setupPropHandler.ts:101:24
     99|  typeParamsPathMembers: any
    100| ): void {
    101|  typeParamsPathMembers.each((prop: NodePath) => {
       |                        ^
    102|   if (bt.isTSPropertySignature(prop.node) && bt.isIdentifier(prop.node.key)) {
    103|    const propDescriptor = documentation.getPropDescriptor(prop.node.key.name)
 ❯ Context.visitCallExpression src/script-setup-handlers/setupPropHandler.ts:49:9
 ❯ Context.invokeVisitorMethod ../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/path-visitor.ts:402:45
 ❯ Visitor.PVp.visitWithoutReset ../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/path-visitor.ts:254:24
 ❯ visitChildren ../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/path-visitor.ts:304:17
 ❯ Visitor.PVp.visitWithoutReset ../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/path-visitor.ts:262:14
 ❯ NodePath.each ../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/path.ts:124:18
 ❯ visitChildren ../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/path-visitor.ts:277:12
 ❯ Visitor.PVp.visitWithoutReset ../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/path-visitor.ts:262:14
```

Essentially, the `Bar` type information specified in defineProps must be
obtained from the AST for the `Foo` referenced by the `Bar`.
However, this error occurs because we are currently only obtaining the
reference type of `Bar`.

This PR does not solve the fundamental problem, but only avoids the
error😓
In the meantime, I would like to avoid the problem of Storybook becoming
unusable due to errors.

---------

Co-authored-by: Barthélémy Ledoux <ledouxb@gmail.com>
Co-authored-by: Barthélémy Ledoux <ledouxb@me.com>